package main

import (
	"golang.org/x/text/language"
)

func Language_en() {
	RegisterTranslations(language.English, map[string]string{
		"介绍1":       "Bestowing eternity upon the fleeting, and warmth to the everlasting night.",
		"介绍2":       "is a utility that automatically renames your visual archives by extracting original capture timestamps.",
		"使用方式":      "Usage: %s [folder_path] or [photo_file_path1] [photo_file_path2] ...\nIf run without providing photo files, it will enter configuration mode.",
		"软件配置":      "Software Configuration",
		"配置文件名命名格式": "Config File Naming Format",
		"当前格式":      "Current renaming format is",
		"要配置格式":     "To configure the renaming format, please run directly without arguments",
		"可用变量":      "Available Variables:\n  <YYYY>/<YY>: Year, <MM>/<M>: Month, <DD>/<D>: Day\n  <HH>/<H>: Hour, <mm>/<m>: Minute, <ss>/<s>: Second\n  <##>: Number (with leading zeros), <#>: Number (without leading zeros)\n  <*>: Original filename\n  Number of letters represents digits, e.g., <YY> for 2025 is 25, <M> for January is 1, <MM> is 01",
		"默认格式例":     "For example, the default format `%s` will output `%s`.\nPlease enter a new filename naming format and press Enter, or leave blank to keep current settings.\n> ",
		"示例输出":      "Example output",
		"格式已设定":     "Format has been set to",
		"询问预览":      "Enable preview confirmation before renaming?",
		"当前设置":      "Current Settings",
		"询问预览说明":    "If enabled, it will show you the changes first for confirmation before proceeding.\nPlease enter `y` or `n`. Default `y`: Always ask me, `n`: Start renaming directly.\n> ",
		"预览确认开":     "Preview confirmation enabled.",
		"预览确认关":     "Preview confirmation disabled. Please proceed with caution.",
		"结束等待":      "After running, do you need to prompt 'Press Enter to exit' to review the results?",
		"结束等待说明":    "Please enter `y` or `n`. Default `y`: Wait for Enter key after completion, `n`: Exit directly after completion.\n> ",
		"结束等待关":     "Exit directly after completion",
		"结束等待开":     "Wait for Enter key after completion",
		"保存配置失败":    "Failed to save configuration to %s: %v",
		"保存配置成功":    "Configuration successfully saved to ",
		"回车退出":      "Press Enter to exit",
		"修改日期":      "File Modification Date",
		"正在分析":      "Analyzing files to be renamed",
		"错误":        "[Error]",
		"跳过":        "[Skip]",
		"路径错误":      "Unable to parse path",
		"文件错误":      "Unable to read photo information",
		"原文件":       "Original File",
		"依据":        "Time Source",
		"新文件名":      "New Filename",
		"没有文件":      "No processable photo files found.",
		"共计":        "Total %d files, ",
		"确认":        "Confirm renaming",
		"开始":        "Starting the renaming process",
		"无变化":       "Filename unchanged",
		"重命名失败":     "[!] Renaming failed!",
		"重命名成功":     "Renaming successful.",
		"已存在":       "Target file already exists.",
		"处理结果":      "[i] Processing complete! Success: %d, Failed: %d, Total: %d",
		"取消":        "Operation cancelled.",
		"非法字符格式":    "The character '%s' is not allowed in this format.",
		"非法字符":      "1. File or folder names cannot include any of the following characters: \\ / : ? ' \" < * > | \n2. The full name of the file or folder cannot be: NUL, COM1 ~ COM9, LPT1 ~ LPT9\n3. The last character cannot be '.' .",
		"重新输入":      "Please try again",
		"获取器":       "Extractor",
		"内置":        "Built-in",
	})
}
